### ISSUE TITLE
can not insert data in relation table

### ISSUE THREAD

**Issue by Mohaymin** [mirarifhasan/QASystem#2]
while trying insertion operation in relation table, I'm getting the follwing error:
```
Traceback (most recent call last):
  File "C:\Users\camoh\AppData\Local\Programs\Python\Python38\lib\site-packages\mysql\connector\conversion.py", line 179, in to_mysql
    return getattr(self, "_{0}_to_mysql".format(type_name))(value)
AttributeError: 'MySQLConverter' object has no attribute '_tuple_to_mysql'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\camoh\AppData\Local\Programs\Python\Python38\lib\site-packages\mysql\connector\cursor.py", line 417, in _process_params
executed query: SELECT * FROM keyword WHERE keyword = 'birthDate'
[(849, 'birthDate', 'birth date')]
executed query: INSERT INTO relation (phraseId, keywordId) VALUES (%s, %s)
    res = [to_mysql(i) for i in res]
  File "C:\Users\camoh\AppData\Local\Programs\Python\Python38\lib\site-packages\mysql\connector\cursor.py", line 417, in <listcomp>
    res = [to_mysql(i) for i in res]
  File "C:\Users\camoh\AppData\Local\Programs\Python\Python38\lib\site-packages\mysql\connector\conversion.py", line 181, in to_mysql
    raise TypeError("Python '{0}' cannot be converted to a "
TypeError: Python 'tuple' cannot be converted to a MySQL type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/All Codes and Projects/Python/QASystem/main.py", line 33, in <module>
    keywordListByDD = byDataDictionary.find_keyword_by_automation(question)
  File "D:\All Codes and Projects\Python\QASystem\q_a_system\method\byDataDictionary.py", line 81, in find_keyword_by_automation
    create_relation(phrase_id, given_keyword)
  File "D:\All Codes and Projects\Python\QASystem\q_a_system\method\byDataDictionary.py", line 108, in create_relation
    insert_double_value(const.COLUMN_PHRASE_ID, const.COLUMN_KEYWORD_ID, phrase_id, keyword_id, const.TABLE_RELATION)
  File "D:\All Codes and Projects\Python\QASystem\q_a_system\method\byDataDictionary.py", line 45, in insert_double_value
    database_cursor.execute(query, value)
  File "C:\Users\camoh\AppData\Local\Programs\Python\Python38\lib\site-packages\mysql\connector\cursor.py", line 539, in execute
    psub = _ParamSubstitutor(self._process_params(params))
  File "C:\Users\camoh\AppData\Local\Programs\Python\Python38\lib\site-packages\mysql\connector\cursor.py", line 421, in _process_params
    raise errors.ProgrammingError(
mysql.connector.errors.ProgrammingError: Failed processing format-parameters; Python 'tuple' cannot be converted to a MySQL type

```

This is the method where I was trying to do the insertion operation:
```
def insert_double_value(column1, column2, value1, value2, table_name):
    query = f'INSERT INTO {table_name} ({column1}, {column2}) VALUES (%s, %s)'
    print(f'executed query: {query}')
    value = (value1, value2)
    database_cursor.execute(query, value)
    database.commit()

```
I've tried using `executemany()`,  `execute()` methods and also changing the datatype of value to list or tuple. but none of it is working.

previously, while experimenting, following method worked:
```
for word in word_list:
    mycursor.execute(sql, [(word)])
    mydb.commit()

```

**Comment by Mohaymin** [comment]
replacing `value = (value1, value2)` with `value = (str(value1), str(value2))` solved the issue
